### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by faisalsaifii** [AzeemIdrisi/ChatterBox#1]
**Suggestion:** Use [TailwindCSS](https://tailwindcss.com/)

Configure the colors in CSS as variables

```css
:root {
  --foreground-color: #000000;
  --background-color: #FFFFFF;
}
```

Use the a media query to get the device theme and change the values of the variables accordingly

```css
@media (prefers-color-scheme: dark) {
  :root {
    --foreground-color: #FFFFFF;
    --background-color: #000000;
  }
}
```
